### ISSUE TITLE
RTSP Proxy

### ISSUE THREAD

**Issue by b23prodtm** [b23prodtm/kerberos-agent#1]
The proxy container's not starting properly
```yml
 mediamtx-rtsp:
    build:
      context: .
      dockerfile: Dockerfile.aarch64
      args:
        TARGETPLATFORM: linux/arm64
    image: betothreeprod/mediamtx
    restart: always
    network_mode: host
    ports:
      - 8554:8554
      - 1935:1935
      - 8888:8888
      - 8889:8889
      - 8890:8890/udp
      - 8189:8189/udp
    privileged: true
    user: root
    environment:
      UDEV: on
      TARGETPLATFORM: linux/arm64
      MTX_PROTOCOLS: tcp
      MTX_WEBRTCADDITIONALHOSTS: videosurveillance
      RTSP_PORT: 8554
      MTX_PATH: usbcam
    volumes:
      - "mediamtx.yml:/mediamtx.yml"
    tmpfs:
      - "/dev/shm:exec"
  ```
